#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill  --randomize ~/.wallpaper/* & 
$HOME/.config/polybar/launch.sh  &

bspc monitor -d I II III IV V VI VII 

bspc config border_width         1
bspc config window_gap           6

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
# bspc config focus_follows_pointer true


bspc config focused_border_color    '#F1F1F1'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome-stable desktop='^2'
bspc rule -a discord desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
